/* TESTING SPONSOR TABLE */
INSERT INTO SPONSOR
VALUES ('S1', 'SPONSOR1', 'JOHN1@GMAIL.COM', 'password');
INSERT INTO SPONSOR
VALUES ('S2', 'SPONSOR2', 'JOHN2@GMAIL.COM', 'password');
INSERT INTO SPONSOR
VALUES ('S3', 'SPONSOR3', 'JOHN3@GMAIL.COM', 'password');

/* TESTING ADMIN TABLE */
INSERT INTO ADMIN
VALUES ('A1', 'ADMIN1', 'ADMIN1@GMAIL.COM', 'password');
INSERT INTO ADMIN
VALUES ('A2', 'ADMIN2', 'ADMIN2@GMAIL.COM', 'password');
INSERT INTO ADMIN
VALUES ('A3', 'ADMIN3', 'ADMIN3@GMAIL.COM', 'password');

/* TESTING DRIVER TABLE */
INSERT INTO DRIVER
VALUES ('D1', 'DRIVER1', 'DRIVER1@GMAIL.COM', 'password', '100');
INSERT INTO DRIVER
VALUES ('D2', 'DRIVER2', 'DRIVER2@GMAIL.COM', 'password', '200');
INSERT INTO DRIVER
VALUES ('D3', 'DRIVER3', 'DRIVER3@GMAIL.COM', 'password', '300');

/* TESTING CATALOG TABLE */
INSERT INTO CATALOG 
VALUES ('I1', 'ITEM1', 'SPONSOR1');
INSERT INTO CATALOG 
VALUES ('I2', 'ITEM2', 'SPONSOR2');
INSERT INTO CATALOG 
VALUES ('I3', 'ITEM3', 'SPONSOR3');

/* TESTING SPONSORED_BY TABLES */
INSERT INTO SPONSORED_BY
VALUES ('S1', 'D1');
INSERT INTO SPONSORED_BY
VALUES ('S2', 'D2');

/* TESTING CAN_VIEW */
INSERT INTO CAN_VIEW
VALUES ('S1', 'D1', 'I1');
INSERT INTO CAN_VIEW
VALUES ('S2', 'D2', 'I2');
INSERT INTO CAN_VIEW
VALUES ('S3', 'D3', 'I3');

/* TESTING MODIFY_SPONSOR */
INSERT INTO MODIFY_SPONSOR
VALUES ('A1', 'S1');
INSERT INTO MODIFY_SPONSOR
VALUES ('A2', 'S2');
INSERT INTO MODIFY_SPONSOR
VALUES ('A3', 'S3');

/* TESTING MODIFY_DRIVER */
INSERT INTO MODIFY_DRIVER
VALUES ('A1', 'D1');
INSERT INTO MODIFY_DRIVER
VALUES ('A2', 'D2');
INSERT INTO MODIFY_DRIVER
VALUES ('A3', 'D3');

/* TESTING ADD_PRODUCTS */
INSERT INTO ADD_PRODUCTS
VALUES ('I1', 'S1', 'PRODUCT LIST 1');
INSERT INTO ADD_PRODUCTS
VALUES ('I2', 'S2', 'PRODUCT LIST 2');
INSERT INTO ADD_PRODUCTS
VALUES ('I3', 'S3', 'PRODUCT LIST 3');

/* TESTING PRODUCT */
INSERT INTO PRODUCT
VALUES ('ITEM NAME1', 'I1');
INSERT INTO PRODUCT
VALUES ('ITEM NAME2', 'I2');
INSERT INTO PRODUCT
VALUES ('ITEM NAME3', 'I3');
